### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by kakaufb** [lucasmazza/lucasmazza.github.io#2]
Oi Lucas, tudo bem?

Eu sou Kakau Fonseca e achei você através do site da Amazon. Estava pesquisando alguns livros e vi o seu livro sobre HTML e CSS. Daí meu email é na verdade com uma dúvida muito honesta:

sou designer de interface e experiência, mas não desenvolvo nada. Você acha que seu livro é pra mim?

Obrigada pela atenção e parabéns pelo livro!

Abs

**Comment by lucasmazza** [comment]
Oi @kakaufb 

Acho que a utilidade do livro vai depender muito do quanto do trabalho técnico você tem interesse ou participa no dia a dia. 

Acho que mesmo sem colocar a mão na massa, o livro pode ajudar a esclarecer alguns tópicos da base de HTML e CSS que devem fazer parte de conversas do dia a dia do seu trabalho de interface/experiência, ou explicar um pouco como algumas partes da web funcionam quando a gente coloca as coisas no ar. Caso contrário, talvez ele não adicione muito dado o seu trabalho atual.

Espero ter esclarecido um pouco 🙈
